export const SHOW_CONTROL_MUSIC = "SHOW_CONTROL_MUSIC"
export const HIDDEN_TABBAR = "HIDDEN_TABBAR"
export const LOAD_COLLECTION = "LOAD_COLLECTION"
export const LOAD_MUSIC = "LOAD_MUSIC"
export const EDIT_MODE = "EDIT_MODE"
export const ADD_ITEM_COLL_EDIT = "ADD_ITEM_COLL_EDIT"
export const REMOVE_ITEM_COLL_EDIT = "REMOVE_ITEM_COLL_EDIT"
export const ADD_ITEM_MUSIC_EDIT = "ADD_ITEM_MUSIC_EDIT"
export const REMOVE_ITEM_MUSIC_EDIT = "REMOVE_ITEM_MUSIC_EDIT"

export const SHOW_POPUP_RENAME = "SHOW_POPUP_RENAME"
export const RESET_EDIT = "RESET_EDIT"

